-- Table for storing invoice drafts (brouillons)
CREATE TABLE IF NOT EXISTS drafts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_name TEXT,
  client_phone TEXT,
  client_address TEXT,
  supplier_name TEXT,
  supplier_phone TEXT,
  supplier_address TEXT,
  date TIMESTAMP WITHOUT TIME ZONE,
  total NUMERIC,
  currency TEXT,
  lines JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Index for faster retrieval by date
CREATE INDEX IF NOT EXISTS idx_drafts_date ON drafts(date DESC);
